{
 "title": "DASHBOARD - OK",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GERAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "POSTGRESQL - 1",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{instance=\"192.168.20.164:9188\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NÓ MASTER (WRITE)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(patroni_primary{name=\"postgresql0\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "NÓ SLAVE (READ)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_replica{job=\"postgresql0\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Transações por segundo",
     "type": "timeseries",
     "description": "Commits e Rollback. \nSELECTs, INSERTs, UPDATEs, DELETEs e CALLs.",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(pg_stat_database_xact_commit[1m])) + sum by(instance) (rate(pg_stat_database_xact_rollback[1m]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Tamanho Total",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(job) (pg_database_size_bytes{job=\"postgresql0\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "POSTGRESQL - 2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{job=\"postgresql1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NÓ MASTER (WRITE)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(patroni_primary{name=\"postgresql1\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "NÓ SLAVE (READ)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_replica{job=\"postgresql1\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "PGPOOL II - NODE 0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Processos filhos ativos",
   "type": "stat",
   "description": "No Pgpool-II, os processos filhos (child processes) são responsáveis por gerenciar conexões entre os clientes (aplicações) e o banco de dados PostgreSQL. O Pgpool-II não conecta cada cliente diretamente ao PostgreSQL; em vez disso, ele mantém um conjunto de conexões pré-abertas para otimizar a performance e reduzir a sobrecarga da criação de novas conexões.\n\nIndica quantos processos filhos o Pgpool-II pode ter em execução ao mesmo tempo, de acordo com a configuração. \n(pgpool.conf >> num_init_children = 32)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_frontend_total{job=\"pgpool0\"}",
     "legendFormat": "Disponível"
    }
   ]
  },
  {
   "title": "Processos filhos em uso",
   "type": "stat",
   "description": "Indica quantos desses processos estão atualmente lidando com conexões de clientes. \n\nSe esse número estiver perto ou igual ao total, pode significar que o Pgpool-II está sobrecarregado, pois atingiu sua capacidade máxima de conexões simultâneas.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (pgpool2_frontend_used{job=\"pgpool0\"})",
     "legendFormat": "Utilizando"
    }
   ]
  },
  {
   "title": "Porcentagem de uso dos processos filhos",
   "type": "timeseries",
   "description": "Indica a relação entre processos filhos em uso e processos filhos disponíveis, expressa como um número entre 0% e 100%.\n\nSe atingir 100%, significa que todas as conexões disponíveis estão sendo usadas, e novas conexões podem ficar bloqueadas ou sofrer latência.",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 2 },
   "targets": [
    {
     "expr": "(sum by(instance) (pgpool2_frontend_used_ratio{job=\"pgpool0\"})) * 100",
     "legendFormat": "Em uso"
    }
   ]
  },
  {
   "title": "INSERTs",
   "type": "timeseries",
   "description": "Mostra a quantidade de inserts sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 2 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_insert_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "DELETEs",
   "type": "timeseries",
   "description": "Mostra a quantidade de deletes sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_delete_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "Status dos Nós Backend",
   "type": "stat",
   "description": "Indica se um nó do banco de dados está ativo ou inativo no Pgpool-II. Com o filtro aplicado:\n\n- ON → O nó está ativo e pode receber conexões do Pgpool-II.\n- OFF → O nó está inativo e não está recebendo conexões.\n\n---\n\nDetalhes técnicos:\n\nO Pgpool-II consulta periodicamente o estado dos nós PostgreSQL.\n\nSe um nó estiver OFF, pode indicar falha na conexão, desativação manual ou remoção do cluster.\n\nEm um ambiente com Patroni, esse valor pode mudar após um failover.",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_pool_nodes_status{job=\"pgpool0\"}",
     "legendFormat": "port: {{port}} | role: {{role}} | {{instance}}"
    }
   ]
  },
  {
   "title": "SELECTs",
   "type": "timeseries",
   "description": "Mostra a quantidade de selects sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_select_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "DDLs",
   "type": "timeseries",
   "description": "Mostra a quantidade de comandos DDL (CREATE, ALTER, DROP) sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_ddl_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "UPDATEs",
   "type": "timeseries",
   "description": "Mostra a quantidade de update sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_update_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "PANIC",
   "type": "timeseries",
   "description": "Número de mensagens PANIC, indicando erros graves que exigem reinicialização do PostgreSQL. \n\nPode ocorrer devido a corrupção de dados ou falha em componentes críticos.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_panic_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "Outras Querys",
   "type": "timeseries",
   "description": "Mostra a quantidade de outros comandos não listados sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.\n\n---  \n\n- BEGIN;\n- COMMIT;\n- ROLLBACK;\n- SAVEPOINT sp1;\n- SHOW ALL;\n- SET work_mem TO '64MB';\n- DISCARD ALL;\n- VACUUM;\n- ANALYZE;\n- CHECKPOINT;\n- SHOW pool_status;\n- CALL minha_procedure();\n\n",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_other_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "ERROR`s",
   "type": "timeseries",
   "description": "Número total de mensagens ERROR, que representam falhas em operações SQL, como constraints violadas, problemas de sintaxe ou tabelas não encontradas.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 26 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_error_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "FATAL",
   "type": "timeseries",
   "description": "Número de mensagens FATAL, que causam a desconexão da sessão. \n\nPode ser resultado de problemas de autenticação, permissões ou bloqueios no banco.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_fatal_cnt{job=\"pgpool0\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  { "title": "PGPOOL II - NODE 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Processos filhos ativos",
   "type": "stat",
   "description": "No Pgpool-II, os processos filhos (child processes) são responsáveis por gerenciar conexões entre os clientes (aplicações) e o banco de dados PostgreSQL. O Pgpool-II não conecta cada cliente diretamente ao PostgreSQL; em vez disso, ele mantém um conjunto de conexões pré-abertas para otimizar a performance e reduzir a sobrecarga da criação de novas conexões.\n\nIndica quantos processos filhos o Pgpool-II pode ter em execução ao mesmo tempo, de acordo com a configuração. \n(pgpool.conf >> num_init_children = 32)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_frontend_total{job=\"pgpool1\"}",
     "legendFormat": "Disponível"
    }
   ]
  },
  {
   "title": "Processos filhos em uso",
   "type": "stat",
   "description": "Indica quantos desses processos estão atualmente lidando com conexões de clientes. \n\nSe esse número estiver perto ou igual ao total, pode significar que o Pgpool-II está sobrecarregado, pois atingiu sua capacidade máxima de conexões simultâneas.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (pgpool2_frontend_used{job=\"pgpool1\"})",
     "legendFormat": "Utilizando"
    }
   ]
  },
  {
   "title": "Taxa de uso dos processos filhos",
   "type": "timeseries",
   "description": "Indica a relação entre processos filhos em uso e processos filhos disponíveis, expressa como um número entre 0% e 100%.\n\nSe atingir 100%, significa que todas as conexões disponíveis estão sendo usadas, e novas conexões podem ficar bloqueadas ou sofrer latência.",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "(sum by(instance) (pgpool2_frontend_used_ratio{job=\"pgpool1\"})) * 100",
     "legendFormat": "Em uso"
    }
   ]
  },
  {
   "title": "INSERTs",
   "type": "timeseries",
   "description": "Mostra a quantidade de inserts sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 38 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_insert_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "Status dos Nós Backend",
   "type": "stat",
   "description": "Indica se um nó do banco de dados está ativo ou inativo no Pgpool-II. Com o filtro aplicado:\n\n- ON → O nó está ativo e pode receber conexões do Pgpool-II.\n- OFF → O nó está inativo e não está recebendo conexões.\n\n---\n\nDetalhes técnicos:\n\nO Pgpool-II consulta periodicamente o estado dos nós PostgreSQL.\n\nSe um nó estiver OFF, pode indicar falha na conexão, desativação manual ou remoção do cluster.\n\nEm um ambiente com Patroni, esse valor pode mudar após um failover.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgpool2_pool_nodes_status{job=\"pgpool1\"}",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "SELECTs",
   "type": "timeseries",
   "description": "Mostra a quantidade de selects sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_select_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "DELETEs",
   "type": "timeseries",
   "description": "Mostra a quantidade de deletes sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 44 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_delete_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "UPDATEs",
   "type": "timeseries",
   "description": "Mostra a quantidade de update sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_update_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "DDLs",
   "type": "timeseries",
   "description": "Mostra a quantidade de comandos DDL (CREATE, ALTER, DROP) sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 50 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_ddl_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "Outras Querys",
   "type": "timeseries",
   "description": "Mostra a quantidade de outros comandos não listados sendo feito através do Pgpool.\n\nPortas:\n- 5433 = postgresql0\n- 5434 = postgresql1\n\nRegras:\n- Primary: servidor primário de escrita e leitura.\n- Standby: servidor segundário apenas para leitura.\n\n---  \n\n- BEGIN;\n- COMMIT;\n- ROLLBACK;\n- SAVEPOINT sp1;\n- SHOW ALL;\n- SET work_mem TO '64MB';\n- DISCARD ALL;\n- VACUUM;\n- ANALYZE;\n- CHECKPOINT;\n- SHOW pool_status;\n- CALL minha_procedure();\n",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_other_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "PANIC",
   "type": "timeseries",
   "description": "Número de mensagens PANIC, indicando erros graves que exigem reinicialização do PostgreSQL. \n\nPode ocorrer devido a corrupção de dados ou falha em componentes críticos.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 56 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_panic_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "FATAL",
   "type": "timeseries",
   "description": "Número de mensagens FATAL, que causam a desconexão da sessão. \n\nPode ser resultado de problemas de autenticação, permissões ou bloqueios no banco.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_fatal_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "ERROR`s",
   "type": "timeseries",
   "description": "Número total de mensagens ERROR, que representam falhas em operações SQL, como constraints violadas, problemas de sintaxe ou tabelas não encontradas.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 62 },
   "targets": [
    {
     "expr": "rate(pgpool2_pool_backend_stats_error_cnt{job=\"pgpool1\"}[1m]) * 100",
     "legendFormat": "port: {{port}} | role: {{role}} "
    }
   ]
  },
  {
   "title": "REPLICAÇÃO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "LAG Replicação",
     "type": "timeseries",
     "description": "Mede o atraso real da replicação no PostgreSQL, indicando quantos segundos os nós secundários estão atrás do nó primário. \n\nUm valor elevado pode impactar a recuperação em caso de failover.",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 254 },
     "targets": [
      { "expr": "pg_replication_lag_seconds", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "WAL Comparação ( Lider / Replica )",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 9, "y": 254 },
     "targets": [
      {
       "expr": "(patroni_xlog_location{scope=\"pg-cluster\"} - patroni_xlog_replayed_location{scope=\"pg-cluster\"}) / 1024 / 1024",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Tamanho WALs ",
     "type": "gauge",
     "description": "Este gráfico exibe o tamanho atual dos arquivos de WAL (Write-Ahead Log) do PostgreSQL para cada nó do cluster. O WAL é essencial para garantir a durabilidade das transações e a replicação entre os servidores.\n\nPor que os tamanhos podem ser diferentes entre os nós?\n\n- O nó primário (Primary) pode gerar mais WALs devido a transações ativas.\n- O nó réplica (Replica) pode ter menos WALs se estiver aplicando as mudanças mais rapidamente.\n- Se a replicação for assíncrona, o replica pode estar atrasado e ter um tamanho menor.\n- Configurações como wal_keep_size e a frequência de checkpoints também influenciam na retenção dos WALs.",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_wal_size_bytes", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "LAG Replicação",
     "type": "timeseries",
     "description": "Mede o atraso de replicação percebido pelo Pgpool-II, baseado na diferença de WALs aplicados entre o nó primário e os nós secundários. \n\nValores altos indicam que o nó secundário pode estar desatualizado para consultas de leitura distribuídas pelo Pgpool-II.\n\n---",
     "gridPos": { "h": 5, "w": 12, "x": 9, "y": 290 },
     "targets": [
      {
       "expr": "group by(port) (pgpool2_pool_nodes_replication_delay)",
       "legendFormat": "port: {{port}} "
      }
     ]
    }
   ]
  },
  {
   "title": "TRANSAÇÕES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consultas Lentas",
     "type": "timeseries",
     "description": "Identifica consultas que podem estar impactando o desempenho do banco.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 255 },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_max_tx_duration) by (datname)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transações por segundo",
     "type": "timeseries",
     "description": "Commits e Rollback. \nSELECTs, INSERTs, UPDATEs, DELETEs e CALLs.",
     "gridPos": { "h": 8, "w": 10, "x": 8, "y": 255 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(pg_stat_database_xact_commit[1m])) + sum by(instance) (rate(pg_stat_database_xact_rollback[1m]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "description": "Esse valor deve estar próximo de 100% para um bom desempenho.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 255 },
     "targets": [
      {
       "expr": "(sum by (datname) (pg_stat_database_blks_hit) / \n sum by (datname) (pg_stat_database_blks_hit + pg_stat_database_blks_read)) * 100\n",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Conexões Ativas ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 277 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(instance) (pg_stat_activity_count)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LOCKS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 277 },
     "targets": [
      {
       "expr": "sum(pg_stat_activity_waiting) by (datname)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PATRONI - NODE 0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "POSTGRESQL - 1",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 256 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{instance=\"192.168.20.164:9188\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NÓ MASTER (WRITE)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 256 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(patroni_primary{name=\"postgresql0\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "NÓ SLAVE (READ)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_replica{job=\"postgresql0\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PATRONI - NODE 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "POSTGRESQL - 2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 773 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{job=\"postgresql1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NÓ MASTER (WRITE)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 773 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(patroni_primary{name=\"postgresql1\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "NÓ SLAVE (READ)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 773 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "patroni_replica{job=\"postgresql1\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SISTEMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memória",
     "type": "timeseries",
     "description": "Uso de memória.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Uso da CPU",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 258 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "description": "mede o tempo que leva para coletar (scrape) as métricas de um alvo específico. Essa métrica é útil para identificar problemas de desempenho ou latência durante a coleta de métricas.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 258 },
     "targets": [
      {
       "expr": "topk(5, max(scrape_duration_seconds) by (job))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Restart Pendente",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 265 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "patroni_pending_restart", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  }
 ]
}